import type { Metadata } from "next";
import constants from "@/infrastructure/constants";
import "./globals.css";
import { AuthProvider } from "@/domain/context/AuthContext";
import { Toaster } from "react-hot-toast";

export const metadata: Metadata = {
  title: constants.app.name,
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`bg-white dark:bg-gray-800`}>
      <body>
        <AuthProvider>
          {children}
          <Toaster position="top-right" reverseOrder={false} />
        </AuthProvider>
      </body>
    </html>
  );
}
